### PR TITLE
Chore - Version Bump to 1.8.1 for WordPress 5.4 Compatibility

### PR DESCRIPTION
**Pull request by coderkoala**
### All Submissions:

* [x] Have you followed the [User Registration Contributing guideline](https://github.com/wpeverest/restaurantpress/blob/master/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Version bump to 1.8.1 to confirm WordPress 5.4 Compatibility.

### How to test the changes in this Pull Request:

1. Navigate to the form builder.
2. Try down-scaling a 3 columns row to 2 columns.
3. Observe that the 3rd (lost column) has its field elements redistributed.

### Types of changes:

* [x] Version Bump
* [ ] Bug fix (non-breaking change which fixes an issue)
* [ ] Enhancement (modification of the currently available functionality)
* [ ] New feature (non-breaking change which adds functionality)
* [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [x] Have you successfully ran tests with your changes locally?
* [x] Have you updated the documentation accordingly?

### Changelog entry

> Chore - Version Bump to 1.8.1 for WordPress 5.4 Compatibility

### CODE REVIEW

**Comment by shivapoudel** [comment]
@coderkoala `Version Bump` text not needed in the changelog. Just include tested up to..

**Comment by shivapoudel** [comment]
Also please update tested up to, plugin version and stable tag in `readme.txt`. Additionally main plugin file plugin version.

**Comment by coderkoala** [comment]
@shivapoudel hopefully eb25523 resolves it :)

**Comment by shivapoudel** [comment]
@coderkoala Please also see another comment just above and fix it :)

**Comment by coderkoala** [comment]
@shivapoudel gotcha! c4a4359 does it, I suppose :)

**Review by shivapoudel — COMMENTED** [review]
LGTM 👍

**Pull request merged**
